"""added Text field to Products

Revision ID: c81e510bbddf
Revises: 4a68f1941bf7
Create Date: 2022-10-31 13:56:42.677613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81e510bbddf'
down_revision = '4a68f1941bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'text')
    # ### end Alembic commands ###
