"""subcategory table fixed

Revision ID: ff688fa37cb9
Revises: 
Create Date: 2022-11-02 00:15:08.331604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff688fa37cb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subategory', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subategory_category_id'), 'subategory', ['category_id'], unique=False)
    op.create_foreign_key(None, 'subategory', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subategory', type_='foreignkey')
    op.drop_index(op.f('ix_subategory_category_id'), table_name='subategory')
    op.drop_column('subategory', 'category_id')
    # ### end Alembic commands ###
